### PR TITLE
Make settings window positioning configurable

### PR DESCRIPTION
**Pull request by uvera**

### CODE REVIEW

**Comment by uvera** [comment]
I rebased this PR to the master branch

**Comment by paperbenni** [comment]
Including multiple iconf and xrandr calls in every sidebar call will make the program feel noticeably slower on low powered machines. My suggestion would be to use environment variables to only read preferences once and then make sidebar behave differently depending on what options are present

**Comment by uvera** [comment]
Yep, you're right, pushed another commit for that change

**Comment by uvera** [comment]
Closing as there's a better implementation merged upstream

**Pull request closed without merging**
